dataThuoc = [
  "NatriCloris 0.9% x 500ml",
  "NatriCloris 0.9% x 100ml",
  "Glucose 5% x 500ml",
  "Glucose 10% x 500ml",
  "Glucose 20% x 500ml",
  "Kali Clorid 1000mg",
  "Calci Clorid 1000mg",
  "Calci Gluconate 1000mg",
  "Nimodipine 30mg",
  "Norepinephrine 4mg",
  "Epinephrine 1mg",
  "Dopamine",
  "Dobutamine",
  "Nitroglycerin",
  "Nitroprusside",
  "Amiodarone",
  "Adenosine 6mg",
  "Atropine",
  "Midazolam",
  "Propofol",
  "Dexmedetomidine",
  "Ketamine",
  "Fentanyl",
  "Morphine 4mg",
  "Paracetamol 500mg",
  "Meropenem 500mg",
  "Imipenem 500mg",
  "Piperacillin/Tazobactam  4.5g",
  "Ceftriaxone 1000mg",
  "Cefepime",
  "Vancomycin 500mg",
  "Linezolid",
  "Levofloxacin 750mg",
  "Colistin 45000IU",
  "Fluconazole 400mg",
  "Voriconazole",
  "Insulin 1000IU",
  "Hydrocortisone 100mg",
  "Methylprednisolone 16mg",
  "Methylprednisolone 4mg",
  "Dexamethasone 4mg",
  "Furosemide 20mg",
  "Spironolactone 25mg",
  "Mannitol 20%",
  "Albumin 20%",
  "Heparin",
  "Enoxaparin 40mg",
  "Warfarin 1mg",
  "Rivaroxaban",
  "Apixaban",
  "Clopidogrel 75mg",
  "Aspirin 81mg",
  "Omeprazole 20mg",
  "Pantoprazole 40mg",
  "Ondansetron",
  "Metoclopramide",
  "Salbutamol 2.5mg",
  "Ipratropium",
  "Acetylcysteine 200mg",
  "Tranexamic acid 500mg",
  "Calcium gluconate 1000mg",
  "Magnesium sulfate",
  "Potassium chloride",
  "Sodium bicarbonate"
];